# Generated by Django 4.2.5 on 2023-11-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_monitor_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='facial_deviations',
        ),
        migrations.AddField(
            model_name='monitor',
            name='copy_paste_attempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitor',
            name='face_deviation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitor',
            name='logins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitor',
            name='logouts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitor',
            name='multiple_face_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitor',
            name='page_minimized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitor',
            name='user_inactivity_detected',
            field=models.BooleanField(default=False),
        ),
    ]
